<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find mir_description)/urdf/general/common_properties.urdf.xacro" />

	<xacro:macro name="actuated_wheel" params="locationprefix locationright">
		<joint name="${locationprefix}_suspension_joint" type="prismatic">
			<origin xyz="0.0 ${-mir_600_act_wheel_dy * locationright} -0.1" rpy="3.141592653589793 0 0"/> <!-- Position relative to base_link -->
			<parent link="base_link"/>
			<child link="${locationprefix}_suspension_link"/>
			<axis xyz="0 0 1"/> <!-- Allow movement along z-axis -->
			<limit lower="-0.2" upper="0.2" effort="1000.0" velocity="0.1"/> <!-- Adjust limits as needed -->
			<!-- Optional: Add Gazebo-specific suspension properties -->
			<gazebo>
				<spring>
				<stiffness>1000.0</stiffness> <!-- Spring stiffness -->
				<damping>50.0</damping>       <!-- Damping coefficient -->
				<reference_position>0.0</reference_position> <!-- Neutral position -->
				</spring>
			</gazebo>
		</joint>
		<link name="${locationprefix}_suspension_link">
			<inertial>
				<mass value="5.0"/> <!-- Adjust mass as needed -->
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/> <!-- Adjust inertia tensor -->
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
				<cylinder length="0.2" radius="0.02"/> <!-- Example geometry for suspension -->
				</geometry>
				<material name="aluminum">
				<color rgba="0.5 0.5 0.5 1"/>
				</material>
			</visual>
		</link>

		<joint name="${locationprefix}_wheel_joint" type="continuous">
			<origin xyz="0.0 0.0 ${mir_600_act_wheel_radius}" rpy="0 0 0" />
			<parent link="${locationprefix}_suspension_link" />
			<child link="${locationprefix}_wheel_link" />
			<axis xyz="0 1 0" />
			<limit effort="200" velocity="20.0" />
		</joint>

		<link name="${locationprefix}_wheel_link">
			<xacro:cylinder_inertial mass="${mir_600_act_wheel_mass}" radius="${mir_600_act_wheel_radius}" length="${mir_600_act_wheel_width}">
				<origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
			</xacro:cylinder_inertial>
			<visual>
				<origin xyz="0 ${locationright * mir_600_act_wheel_width*0.5} 0" rpy="${pi * 0.5} 0 ${0.5 * pi * (1+ locationright)}" />
				<geometry>
					<mesh filename="package://mir_description/meshes/visual/mir_600_wheel.stl" />
				</geometry>
				<xacro:insert_block name="material_dark_grey" />
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="${pi * 0.5} 0 ${pi * -1}" />
				<geometry>
					<cylinder radius="${mir_600_act_wheel_radius}" length="${mir_600_act_wheel_width}"/>
				</geometry>
			</collision>
		</link>
	</xacro:macro>

	<xacro:macro name="caster_wheel" params="locationprefix locationright wheel_base_dx">
		<!-- caster hub -->
		<joint name="${locationprefix}_caster_rotation_joint" type="continuous">
			<origin xyz="${wheel_base_dx} ${-mir_600_caster_wheel_base_dy * locationright} ${mir_600_caster_wheel_base_dz}" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="${locationprefix}_caster_rotation_link" />
			<axis xyz="0 0 1" />
			<dynamics damping="0.01" friction="0.0"/>
		</joint>

		<!-- Caster Suspensions -->
		<joint name="${locationprefix}_caster_suspension_joint" type="prismatic">
			<origin xyz="0.0 -0.0 -0.0" rpy="0 0 0"/> <!-- Position relative to base_link -->
			<parent link="${locationprefix}_caster_rotation_link"/>
			<child link="${locationprefix}_caster_suspension_link"/>
			<axis xyz="0 0 -1"/> <!-- Allow movement along z-axis -->
			<limit lower="-0.0" upper="0.2" effort="1000000.0" velocity="0.1"/> <!-- Adjust limits as needed -->
			<!-- Optional: Add Gazebo-specific suspension properties -->
			<gazebo>
				<spring>
				<stiffness>1000.0</stiffness> <!-- Spring stiffness -->
				<damping>50.0</damping>       <!-- Damping coefficient -->
				<reference_position>0.1</reference_position> <!-- Neutral position -->
				</spring>
			</gazebo>
		</joint>

		<link name="${locationprefix}_caster_suspension_link">
			<inertial>
				<mass value="5.0"/> <!-- Adjust mass as needed -->
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/> <!-- Adjust inertia tensor -->
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
				<cylinder length="0.2" radius="0.02"/> <!-- Example geometry for suspension -->
				</geometry>
				<material name="aluminum">
				<color rgba="0.5 0.5 0.5 1"/>
				</material>
			</visual>
		</link>

		<link name="${locationprefix}_caster_rotation_link">
		<inertial>
			<!-- <origin xyz="0 0 -0.042500000044" rpy="${0.5 * pi} ${24 * deg_to_rad} ${1.5 * pi}" /> -->
			<origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi} " />
			<mass value="0.3097539019" />
			<inertia
				ixx="0.0005844517978"
				ixy="0"
				ixz="0"
				iyy="0.00052872551237"
				iyz="0"
				izz="0.00017923555074" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://mir_description/meshes/visual/caster_wheel_base.stl" />
			</geometry>
			<xacro:insert_block name="material_silver" />
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://mir_description/meshes/collision/caster_wheel_base.stl" />
			</geometry>
		</collision>
		</link>

		<!-- caster wheel -->
		<joint name="${locationprefix}_caster_wheel_joint" type="continuous">
			<origin xyz="${mir_600_caster_wheel_dx} ${-mir_600_caster_wheel_dy * locationright} ${mir_600_caster_wheel_dz}" rpy="0 0 0" />
			<parent link="${locationprefix}_caster_suspension_link" />
			<child link="${locationprefix}_caster_wheel_link" />
			<axis xyz="0 1 0" />
		</joint>

		<link name="${locationprefix}_caster_wheel_link">
			<xacro:cylinder_inertial mass="${mir_600_caster_wheel_mass}" radius="${mir_600_caster_wheel_radius}" length="${mir_600_caster_wheel_width}">
				<origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
			</xacro:cylinder_inertial>
			<visual>
				<origin xyz="0 0 0" rpy="${pi * 0.5} 0 0" />
				<geometry>
					<mesh filename="package://mir_description/meshes/visual/mir_600_caster_wheel.stl" />
				</geometry>
				<xacro:insert_block name="material_dark_grey" />
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="${pi * 0.5} 0 0" />
				<geometry>
					<cylinder radius="${mir_600_caster_wheel_radius}" length="${mir_600_caster_wheel_width}"/>
				</geometry>
			</collision>
		</link>
	</xacro:macro>
</robot>