name: Build and Launch Robot in Gazebo

on:
  push:
    branches: [noetic-devel]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        rosdistro: [noetic]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: osrf/ros:noetic-desktop-full
    steps:
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang-format-10 file git python3-catkin-lint \
            python3-catkin-tools python3-pip python3-rosdep

      - name: Install pip dependencies
        run: pip install pre-commit

      - name: Set up Catkin workspace
        run: |
          # Create the correct workspace directory structure
          mkdir -p /__w/catkin_ws/src
          cd /__w/catkin_ws
          catkin init

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: /__w/catkin_ws/src/match_mobile_robotics  # Checkout into src/match_mobile_robotics

      - name: Install remaining dependencies
        run: |
          cd /__w/catkin_ws/src/match_mobile_robotics
          bash setup_github.sh
          cd /__w/catkin_ws
          if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
            sudo rosdep init
          fi
          rosdep update
          rosdep install --from-paths src -i -y --rosdistro ${{ matrix.rosdistro }}

      - name: Clean workspace (optional but recommended for fresh builds)
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.sh
          cd /__w/catkin_ws
          catkin clean -y || true  # Clean the workspace if it exists

      - name: Build workspace
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.sh
          cd /__w/catkin_ws
          catkin build --limit-status-rate 0.1 --no-notify
          catkin build --limit-status-rate 0.1 --no-notify --make-args tests

      - name: Source environment
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.sh
          source /__w/catkin_ws/devel/setup.sh  # Source the workspace environment

      - name: Debug workspace packages
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.sh
          source /__w/catkin_ws/devel/setup.sh
          echo "Listing available ROS packages:"
          rospack list  # List all packages, should include your workspace packages
          echo "ROS_PACKAGE_PATH: $ROS_PACKAGE_PATH"

      - name: Launch Gazebo with Robot
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.sh
          source /__w/catkin_ws/devel/setup.sh
          roslaunch mir_examples single_mir_600.launch

      - name: Run pre-commit hooks
        run: |
          cd /__w/catkin_ws/src/match_mobile_robotics
          pre-commit run -a
