name: Build and Launch Robot in Gazebo on Macbook

on:
  push:
    branches: [noetic-devel]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        rosdistro: [noetic]
    runs-on: 
      - self-hosted
      - macbook
    steps:
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update

      - name: Install dependencies with Homebrew
        run: |
          brew install clang-format git cmake
          brew install python3 catkin-tools
          brew install ros-noetic-desktop-full  # You will need to ensure ROS is properly installed on macOS

      - name: Install pip dependencies
        run: pip3 install pre-commit

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: src/match_mobile_robotics

      - name: install remaining dependencies
        run: |
          cd src/match_mobile_robotics
          bash setup_github.sh
          cd ../..
          rosdep update
          rosdep install --from-paths src -i -y --rosdistro ${{ matrix.rosdistro }}

      - name: Build
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.sh
          catkin init
          catkin config -j 1 -p 1
          catkin build --limit-status-rate 0.1 --no-notify
          catkin build --limit-status-rate 0.1 --no-notify --make-args tests

      - name: Source environment
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.sh
          source devel/setup.sh

      - name: Launch Gazebo with Robot
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.sh
          source devel/setup.sh
          roslaunch <your_robot_package> <your_robot_launch_file>.launch

      - name: Run pre-commit hooks
        run: |
          cd src/match_mobile_robotics
          pre-commit run -a
